/**
 * Szabó Music Company — Language System
 * Supports: English (en) | Hungarian (hu)
 */
const TRANSLATIONS = {
  en: {
    "nav.home":"Homepage","nav.about":"About Us","nav.artists":"Artists","nav.artists.world":"World Class Musicians","nav.artists.roster":"Full Roster","nav.artists.musicians":"Musicians","nav.contact":"Contact","nav.book":"Book Talent",
    "hero.tagline":"Est. Budapest, Hungary","hero.title":"Szabó Music Company","hero.subtitle":"Where World-Class Musicians Meet World-Class Voyages","hero.desc":"Curating once in a lifetime musical experiences for the luxury cruise and hotel industry.","hero.showreel":"Watch Showreel","hero.discover":"Discover",
    "services.label":"What We Offer","services.title":"Our Services","services.desc":"Curating world-class musical experiences for the luxury cruise industry. Bringing elegance and class to every corner of the world.","services.curation.title":"Talent Curation","services.curation.desc":"We've been trusted by the world's largest travel companies, and the best musicians since XXXX. We provide outstanding service with a long list of testimonials.","services.partner.title":"Cruise Partnerships","services.partner.desc":"Direct relationships with leading cruise lines worldwide, facilitating seamless placements for multi-month contracts.","services.mgmt.title":"Artist Management","services.mgmt.desc":"Full-service management including contracts, travel logistics, visas, and ongoing performance support.","services.trust.title":"Trustworthy and Reliable","services.trust.desc":"We have built a decade long resume with the best musicians and businesses in the hospitality industry.",
    "about.label":"About Us","about.title":"The Bridge Between","about.title.accent":"Talent & Opportunity","about.p1":"Founded in Budapest, Szabo Music Company has been the premier connection between exceptional European musicians and the world's most prestigious cruise lines. Our deep understanding of both the music industry and maritime entertainment creates unparalleled opportunities for artists and cruise companies alike.","about.p2":"Miklos Szabo is a graduate of the Franz Liszt Academy of Music in Budapest, Hungary. He has made his mark as maritime musician performing for industry leading cruise lines, notably Holland America Line, Viking Ocean Cruises, P&O Cruises and Cunard Line. His decade long experience has taken him around the world and earned him a wealth of insights and connections in the music business. Miklos takes pride in overseeing the development of young musicians, arranging the right position for the right performer and providing professional management to clients.","about.location":"Budapest, Hungary","about.since":"Since XXXX","about.reach":"Global Reach","about.founder.name":"Miklos Szabó","about.founder.role":"Founder & Director",
    "talent.title":"World Class Musicians","talent.desc":"Bringing elegance and class to every corner of the world.","talent.view":"View Full Roster","talent.soloist":"Soloist","talent.pianist":"Pianist","talent.duo":"Duo",
    "contact.label":"Get In Touch","contact.title":"Start Your Journey","contact.desc":"Whether you're a musician seeking opportunities or a cruise line looking for talent, we'd love to hear from you","contact.fname":"First Name","contact.lname":"Last Name","contact.email":"Email","contact.type":"I am a...","contact.type.opt0":"Select an option","contact.type.opt1":"Musician seeking opportunities","contact.type.opt2":"Cruise line representative","contact.type.opt3":"Other inquiry","contact.message":"Message","contact.send":"Send Message","contact.office":"Our Office","contact.emailus":"Email Us","contact.callus":"Call Us","contact.response":"Response Time","contact.response.v":"We typically respond within 24 hours during business days","contact.fn.ph":"John","contact.ln.ph":"Smith","contact.email.ph":"john@example.com","contact.msg.ph":"Tell us about your requirements...",
    "partners.label":"Trusted by the World's Finest Fleets",
    "footer.desc":"The premier talent agency for the global cruise industry. Connecting luxury fleets with world-class performers since XXXX.","footer.company":"Company","footer.company.about":"About Us","footer.company.careers":"Careers","footer.company.press":"Press","footer.company.contact":"Contact","footer.talent":"For Talent","footer.talent.submit":"Submit Profile","footer.talent.auditions":"Auditions","footer.talent.resources":"Artist Resources","footer.talent.faqs":"FAQs","footer.contact":"Contact","footer.copyright":"© 2024 Szabo Music Company. All rights reserved.","footer.privacy":"Privacy Policy","footer.terms":"Terms of Service",
    "musicians.title":"Our Musicians","musicians.desc":"Discover exceptional talent across all musical formats. From intimate solo performances to grand ensembles, we represent world-class musicians for the luxury cruise industry.","musicians.solos.title":"Solo Acts","musicians.solos.desc":"Intimate, versatile performers who command any stage with effortless artistry.","musicians.duos.title":"Duos","musicians.duos.desc":"Dynamic pairings that blend seamlessly into any atmosphere, from cocktail hour to dinner service.","musicians.bands.title":"Bands","musicians.bands.desc":"Full ensembles that transform any venue into a world-class concert experience.","musicians.see":"See All","musicians.cta.title":"Ready to Book World-Class Talent?","musicians.cta.desc":"Connect with our team to discover the perfect musicians for your cruise line. From intimate performances to grand showcases, we have talent for every venue.","musicians.cta.btn":"Get in Touch",
    "soloists.breadcrumb":"Musicians","soloists.section":"Our Roster","soloists.breadcrumb.cur":"Solo Acts","soloists.title":"Solo Acts","soloists.desc":"Intimate, versatile, unforgettable. Our soloists bring world-class artistry to every stage — from the grand atrium to the private lounge.",
    "bands.section":"Our Roster","bands.breadcrumb.cur":"Bands","bands.title":"Bands & Ensembles","bands.desc":"Intimate, virtuosic, unforgettable. Our bands bring world-class artistry to every stage — from the main showroom to the private lounge.",
    "duos.section":"Our Roster","duos.breadcrumb.cur":"Duos","JQ":"Jazz Quartet","JS":"Jazz Sextet","partyband":"Party Band","duos.title":"Duos","duos.desc":"Chemistry, contrast, and conversation in music. Our duos create an intimate dynamic that elevates any setting.",
    "roster.cta.title":"Ready to Book World-Class Talent?","roster.cta.desc":"Connect with our team to find the perfect artist for your vessel and venue.","roster.cta.btn":"Get in Touch","roster.show_all":"Show All Artists",
    "role.cocktail_pianist":"Cocktail Pianist","role.stowaway_pianist":"Stowaway Pianist","role.piano_vocalist":"Piano Vocalist","role.guitar_vocalist":"Guitar Vocalist","role.dj_sax":"DJ / Sax","role.solo_guitarist":"Solo Guitarist","role.piano_bar":"Piano Bar Entertainer","role.vocal_duo":"Vocal Duo","role.duo":"Duo","role.acoustic_duo":"Acoustic Duo","musicians.solos.desc": "Represents a hand-picked collection of exceptional solo artists, spanning the full spectrum of solo performance — from DJ/Saxophone and classical piano to guitar and piano vocals. Each act brings their own distinct voice to the world's most prestigious cruise ships, hotel lounges and grand atriums. Whether setting the mood for an elegant dinner or turning a room into an event, every artist we represent shares one rare quality: the ability to hold a room, alone.",

"musicians.duos.desc": "Our duo roster spans the full range of live performance — from intimate acoustic jazz pairings of piano and voice, to high-energy acts blending live instrumentation with cutting-edge backing tracks. Each duo is carefully selected to adapt seamlessly to any setting, whether a candlelit lounge, a poolside deck, or a full-scale evening show. From sophisticated background ambience to a crowd-filling party set, our duos deliver twice the artistry with all the versatility the world's finest venues demand.",

"musicians.bands.desc": "Brings the full power of live ensemble performance to the world's most prestigious stages — from swinging jazz quartets and sextets to high-energy party bands that fill any dance floor. Each group is handpicked for their professionalism, versatility and ability to read a room, shifting effortlessly from elegant cocktail jazz to a euphoric late-night set. Whether gracing a black-tie gala or igniting an on-board party night, our groups deliver the kind of live music experience that guests simply never forget.",
  },
  hu: {
    "nav.home":"Főoldal","nav.about":"Rólunk","nav.artists":"Előadók","nav.artists.world":"Világszínvonalú Zenészek","nav.artists.roster":"Teljes Névsor","nav.artists.musicians":"Zenészek","nav.contact":"Kapcsolat","nav.book":"Előadó Foglalása",
    "hero.tagline":"Alapítva. Budapest, Magyarország","hero.title":"Szabó Music Company","hero.subtitle":"Ahol Világszínvonalú Zenészek Találkoznak Világ Körüli Utazásokkal","hero.desc":"Egyedülálló zenei élményeket kínálunk a luxushajózási és szállodai ipar számára.","hero.showreel":"Showreel Megtekintése","hero.discover":"Felfedezés",
    "services.label":"Amit Kínálunk","services.title":"Szolgáltatásaink","services.desc":"Világszínvonalú zenei élményeket kínálunk a luxushajózási ipar számára. Eleganciát és stílust hozunk a világ minden szegletébe.","services.curation.title":"Tehetségkiválasztás","services.curation.desc":"XXXX óta a világ legnagyobb utazási vállalatai és a legjobb zenészek egyaránt megbíznak bennünk. Kiemelkedő szolgáltatást nyújtunk, amelyet hosszú referencialistánk is igazol.","services.partner.title":"Hajótársasági Partnerségek","services.partner.desc":"Közvetlen kapcsolataink vannak a világ vezető hajóstársaságaival, amelyek zökkenőmentes elhelyezést tesznek lehetővé több hónapos szerződések keretében.","services.mgmt.title":"Előadókezelés","services.mgmt.desc":"Teljes körű menedzsment, beleértve a szerződéseket, utazáslogisztikát, vízumokat és a folyamatos előadói támogatást.","services.trust.title":"Megbízható és Kiszámítható","services.trust.desc":"Évtizedes tapasztalatot szereztünk a legjobb zenészekkel és a vendéglátóipar legjobb vállalkozásaival együttműködve.",
    "about.label":"Rólunk","about.title":"A Híd","about.title.accent":"Tehetség és Lehetőség Között","about.p1":"Budapesten alapítva, a Szabó Music Company az európai kivételes zenészek és a világ legtekintélyesebb hajóstársaságai közötti legfontosabb összekötő kapoccsá vált. A zeneipar és a hajózási szórakoztatás mélységes ismerete páratlan lehetőségeket teremt mind a zenészek, mind a hajóstársaságok számára.","about.p2":"Szabó Miklós a budapesti Franz Liszt Zeneakadémia végzőse. Tengerészeti zenészként meghatározó nyomot hagyott maga után az iparban, előadva a vezető hajóstársaságok számára, köztük a Holland America Line, Viking Ocean Cruises, P&O Cruises és Cunard Line fedélzetein. Évtizedes tapasztalata a világ minden szegletébe elvitte, és értékes kapcsolatokat, betekintést szerzett a zenei üzletágban. Miklós büszkén vállalja a fiatal zenészek fejlődésének irányítását, a megfelelő pozíció megtalálását a megfelelő előadónak, és professzionális menedzsmentet nyújt ügyfeleinek.","about.location":"Budapest, Magyarország","about.since":"XXXX óta","about.reach":"Globális Jelenlét","about.founder.name":"Szabó Miklós","about.founder.role":"Alapító & Igazgató",
    "talent.title":"Világszínvonalú Zenészek","talent.desc":"Eleganciát és stílust hozunk a világ minden szegletébe.","talent.view":"Teljes Névsor Megtekintése","talent.soloist":"Szólista","talent.pianist":"Zongorista","talent.duo":"Duó",
    "contact.label":"Lépjen Kapcsolatba","contact.title":"Kezdje El Az Utazást","contact.desc":"Akár zenész, aki lehetőségeket keres, akár hajóstársaság, amely tehetséget szeretne foglalni — szívesen halljuk Önt","contact.fname":"Keresztnév","contact.lname":"Vezetéknév","contact.email":"E-mail","contact.type":"Én vagyok...","contact.type.opt0":"Válasszon egy lehetőséget","contact.type.opt1":"Lehetőségeket kereső zenész","contact.type.opt2":"Hajóstársaság képviselője","contact.type.opt3":"Egyéb megkeresés","contact.message":"Üzenet","contact.send":"Üzenet Küldése","contact.office":"Irodánk","contact.emailus":"Írjon Nekünk","contact.callus":"Hívjon Minket","contact.response":"Válaszidő","contact.response.v":"Általában 24 órán belül válaszolunk munkanapokon","contact.fn.ph":"Kovács","contact.ln.ph":"János","contact.email.ph":"kovacs.janos@pelda.hu","contact.msg.ph":"Írja le igényeit...",
    "partners.label":"A Világ Legjobb Flottái Bíznak Bennünk",
    "footer.desc":"A globális hajózási ipar vezető tehetségügynöksége. Luxusflottákat kötünk össze világszínvonalú előadókkal XXXX óta.","footer.company":"Cég","footer.company.about":"Rólunk","footer.company.careers":"Karrier","footer.company.press":"Sajtó","footer.company.contact":"Kapcsolat","footer.talent":"Előadóknak","footer.talent.submit":"Profil Beküldése","footer.talent.auditions":"Meghallgatások","footer.talent.resources":"Előadói Erőforrások","footer.talent.faqs":"GYIK","footer.contact":"Kapcsolat","footer.copyright":"© 2024 Szabo Music Company. Minden jog fenntartva.","footer.privacy":"Adatvédelmi Szabályzat","footer.terms":"Szolgáltatási Feltételek",
    "musicians.title":"Zenészeink","musicians.desc":"Fedezzen fel kivételes tehetségeket minden zenei formátumban. Intim szólóelőadásoktól a nagyzenekarokig — a luxushajózási ipar számára képviselünk világszínvonalú zenészeket.","musicians.solos.title":"Szólóelőadók","musicians.solos.desc":"Intim, sokoldalú előadók, akik könnyedén uralnak bármilyen színpadot.","musicians.duos.title":"Duók","musicians.duos.desc":"Dinamikus párosok, amelyek zökkenőmentesen illeszkednek bármilyen hangulatba, a koktélóráktól a vacsorafelszolgálásig.","musicians.bands.title":"Zenekarok","musicians.bands.desc":"Teljes együttesek, amelyek bármely helyszínt világszínvonalú koncertélménnyé varázsolnak.","musicians.see":"Összes Megtekintése","musicians.cta.title":"Készen Áll Foglalni?","musicians.cta.desc":"Vegye fel a kapcsolatot csapatunkkal, hogy megtalálja a tökéletes zenészeket hajóstársasága számára.","musicians.cta.btn":"Kapcsolatfelvétel",
    "soloists.breadcrumb":"Zenészek","soloists.section":"Névsorunk","soloists.breadcrumb.cur":"Szólóelőadók","soloists.title":"Szólóelőadók","soloists.desc":"Intim, sokoldalú, felejthetetlen. Szólistáink világszínvonalú művészetet hoznak minden színpadra — a nagy aulától a privát szalonig.",
    "bands.section":"Névsorunk","bands.breadcrumb.cur":"Zenekarok","bands.title":"Zenekarok & Együttesek","bands.desc":"Intim, virtuóz, felejthetetlen. Zenekararaink világszínvonalú előadóművészetet hoznak minden színpadra — a főszínháztól a privát szalonig.",
    "duos.section":"Névsorunk","JQ":"Jazz Quartet","JS":"Jazz Sextet","partyband":"Party Zenekar","duos.breadcrumb.cur":"Duók","duos.title":"Duók","duos.desc":"Kémia, kontraszt és zenei párbeszéd. Duóink intim dinamikát teremtenek, amely minden helyszínt felemelvé tesz.",
    "roster.cta.title":"Készen Áll Foglalni?","roster.cta.desc":"Vegye fel a kapcsolatot csapatunkkal, hogy megtalálja a tökéletes előadót az Ön hajójára és helyszínére.","roster.cta.btn":"Kapcsolatfelvétel","roster.show_all":"Összes Előadó Megtekintése",
    "role.cocktail_pianist":"Koktélzongorista","role.stowaway_pianist":"Stowaway Zongorista","role.piano_vocalist":"Zongora-énekes","role.guitar_vocalist":"Gitáros Énekes","role.dj_sax":"DJ / Szaxofon","role.solo_guitarist":"Szóló Gitáros","role.piano_bar":"Piano Bar Szórakoztató","role.vocal_duo":"Énekes Duó","role.duo":"Duó","role.acoustic_duo":"Akusztikus Duó", "musicians.solos.desc": "Gondosan válogatott szólóelőadóink a teljes előadóművészeti spektrumot lefedik — DJ/szaxofontól és klasszikus zongorától egészen a gitáros és zongorás énekesekig. Minden előadó egyedi hangot és karaktert hoz a világ legelőkelőbb hajóinak nagyszínpadaira, szállodai szalonjaira és impozáns atriumaiba. Legyen szó egy elegáns vacsora hangulatának megteremtéséről vagy egy egész termet magával ragadó estről — előadóinkat egyetlen ritka képesség köti össze: a jelenlét, amellyel egyedül is uralnak egy szobát.",

"musicians.duos.desc": "Duóink repertoárja a legintimebb akusztikus jazz-párositásoktól — zongora és ének — egészen a live hangszert és modern backingtracket ötvöző, energikus produkciókig terjed. Minden duót gondosan válogatunk, hogy bármilyen helyszínre zökkenőmentesen illeszkedjék — legyen az gyertyafényes szalon, medencedeck vagy nagyszabású esti show. A kifinomult háttérzenétől a táncra hívó party-setig duóink kétszeres művészi erőt és a világ legjobb helyszínei által megkövetelt teljes sokoldalúságot nyújtják.",

"musicians.bands.desc": "Zenekararaink a live ensemble-előadás teljes erejét viszik a világ legelőkelőbb színpadaira — a swingező jazz-kvartettektől és szextettektől egészen a táncteret megtöltő, nagy energiájú party-zenekarokig. Minden együttest a professzionalizmusuk, sokoldalúságuk és a közönség hangulatára való érzékenységük alapján választunk ki — képesek elegáns koktél-jazzből euforikus késő esti showba átváltani. Akár díszvacsorán lépnek fel, akár fedélzeti party-éjszakát gyújtanak be, zenekararaink olyan élő zenei élményt nyújtanak, amelyet a vendégek egyszerűen nem felejtenek el."
  }
};

const DEFAULT_LANG = 'en';
function getCurrentLang(){return localStorage.getItem('smc-lang')||DEFAULT_LANG;}
function setLang(lang){localStorage.setItem('smc-lang',lang);applyLang(lang);document.documentElement.lang=lang;}
function applyLang(lang){
  const dict=TRANSLATIONS[lang]||TRANSLATIONS[DEFAULT_LANG];
  document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[k]!==undefined)el.textContent=dict[k];});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(dict[k]!==undefined)el.placeholder=dict[k];});
  document.querySelectorAll('[data-i18n-aria]').forEach(el=>{const k=el.dataset.i18nAria;if(dict[k]!==undefined)el.setAttribute('aria-label',dict[k]);});
  document.querySelectorAll('.lang-toggle-btn').forEach(btn=>{
    const en=btn.querySelector('.lang-en'),hu=btn.querySelector('.lang-hu');
    if(en&&hu){en.classList.toggle('lang-active',lang==='en');hu.classList.toggle('lang-active',lang==='hu');}
  });
}
function toggleLang(){setLang(getCurrentLang()==='en'?'hu':'en');}
document.addEventListener('DOMContentLoaded',()=>{
  const lang=getCurrentLang();document.documentElement.lang=lang;applyLang(lang);
  document.querySelectorAll('.lang-toggle-btn').forEach(btn=>btn.addEventListener('click',toggleLang));
});
